---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          imagePullPolicy: "Always"
          image: nguu0123/web-server
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30004
  selector:
    app: web-server
  type: NodePort
