[tool.rye]
dev-dependencies = [
  "pre-commit",
  "ruff",
  "codespell",
  "pip>=24.2",
  "pytest>=8.3.2",
  "tox>=4.18.0",
  "pytest-sugar>=1.0.0",
  "tox-uv>=1.11.2",
  "tox-gh-actions>=3.2.0",
]
managed = true
universal = true


[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 10

[tool.ruff.lint.pydocstyle]
convention = "pep257" # Accepts: "google", "numpy", or "pep257".

[tool.ruff.lint]
exclude = ["src/inference-server/darknet.py"]
select = [
  "F",   # Pyflakes
  "E",   # Pycode styles
  "W",   # Pycode styles
  "N",   # Pep8 naming
  "I",   # Isort
  "UP",  # Pyupgrade
  "C4",  # Flake8 comprehension
  "ISC", # Flake8 implicit str concat
  "B",   # Flake8 bugbear
  "PGH", # Pygrep hook
  "RUF", # Ruff specific rules
]
ignore = [
  "E501",   # Line too long
  "RET504", # Unnecessary assignment
  "RET505", # Unnecessary else after return
  "C901",   # Too complex function
  "B904",   # raise-without-from-inside-except, enable when understand more
  "PLR",
  "ISC001",
]

[tool.rye.lint.pylint]
max-args = 10
